### PR TITLE
fix: add debug information

### PR DESCRIPTION
**Pull request by Jing-ze**
## Description
Add debug information for OAuth2 process

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

### CODE REVIEW

**Comment by johnlanni** [comment]
cc  @rinfx

**Comment by johnlanni** [comment]
@Jing-ze Please resolve the conflicts

**Comment by Jing-ze** [comment]
> @Jing-ze Please resolve the conflicts

resolved

**Review by johnlanni — APPROVED** [review]
LGTM

**Pull request merged**
